# Generated by Django 5.0.2 on 2024-04-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0005_remove_mascotas_especie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_cita', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Done', 'DONE'), ('Canceled', 'CANCELED')], default='Done', max_length=10)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.mascotas')),
            ],
            options={
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
