# Generated by Django 5.0.2 on 2024-04-18 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0006_citas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desparasitaciones',
            fields=[
                ('id_desparasitacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('status', models.CharField(choices=[('Completado', 'COMPLETADO'), ('No completado', 'No completado')], default='Completado', max_length=20)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.mascotas')),
            ],
            options={
                'verbose_name_plural': 'Desparasitaciones',
            },
        ),
    ]
